services:
  app:
    build: .
    restart: unless-stopped
    stdin_open: true  # allows interactive input to be sent to the container
    tty: true         # allows for interactive terminal for input above
    environment:
      - PYTHONUNBUFFERED=1  # makes Python print outputs immediately
    secrets:
      - api_keys_env
    # The app will run as non-root user 'appuser'
    # as defined in the Dockerfile

secrets:
  api_keys_env:
    file: ./api-keys/.env

# Note: Requires Docker Compose plugin (included with modern Docker installations)
# Use command: docker compose up --build
