# required for packages
install.packages("data.table")
install.packages("dplyr")
#install.packages("methods")
install.packages("readr")
install.packages("scales")
#install.packages("stats")
install.packages("stringr")
install.packages("tibble")
install.packages("tidyselect")
#install.packages("MASS")
install.packages("fastDummies")
#install.packages("openxlsx")
#install.packages("openxlsx_4.2.5.9002.tar.gz", repos = NULL, type = "source")
install.packages("testthat")
install.packages("devtools")
install.packages("roxygen2")
install.packages("lintr")
install.packages("covr")
#install.packages("oysteR")
install.packages("lmtest")
install.packages("magrittr")
#install.packages("Matrix")
install.packages("nortest")
install.packages("santoku")
install.packages("stringi")
#install.packages("utils")
install.packages("readxl")
install.packages("tm")
install.packages("gets")
#install.packages("grDevices")
# install.packages("paramtest")
install.packages("jsonlite")
install.packages('tidyr')

# required for pea1.R
install.packages("future")

# good for dev run
install.packages("here")
